#!/usr/bin/env python3
"""
Costco Price Checker using Web Scraping
This script checks Costco prices by scraping product pages and creates GitHub issues for alerts.

Exit Codes:
- 0: No price alerts (all prices above threshold) - workflow passes
- 1: Price alert triggered (price at/below threshold) - workflow fails to send notification
"""

import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

# For GitHub Actions
import requests
from bs4 import BeautifulSoup


def load_config():
    """Load configuration from config.json"""
    config_path = Path(__file__).parent / "config.json"
    with open(config_path, 'r') as f:
        return json.load(f)


def load_price_history():
    """Load price history from JSON file"""
    history_path = Path(__file__).parent / "price_history.json"
    if history_path.exists():
        with open(history_path, 'r') as f:
            return json.load(f)
    return {}


def save_price_history(history):
    """Save price history to JSON file"""
    history_path = Path(__file__).parent / "price_history.json"
    with open(history_path, 'w') as f:
        json.dump(history, f, indent=2)


def scrape_price_from_product_page(url):
    """
    Scrape price from Costco product page
    
    Args:
        url: Product page URL
        
    Returns:
        tuple: (price, product_name) or (None, None) if failed
    """
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # Try to find price using common Costco price selectors
        price_text = None
        product_name = None
        
        # Method 1: Look for price in meta tags
        price_meta = soup.find('meta', {'property': 'product:price:amount'})
        if price_meta:
            price_text = price_meta.get('content')
        
        # Method 2: Look for data-testid price
        if not price_text:
            price_elem = soup.find(attrs={'data-testid': 'Text_single-price-whole-value'})
            if price_elem:
                price_text = price_elem.get_text()
        
        # Method 3: Look for price in common class names
        if not price_text:
            price_selectors = [
                {'class': 'price'},
                {'class': 'value'},
                {'itemprop': 'price'}
            ]
            for selector in price_selectors:
                elem = soup.find(attrs=selector)
                if elem:
                    price_text = elem.get_text()
                    break
        
        # Get product name
        title_elem = soup.find('h1')
        if title_elem:
            product_name = title_elem.get_text().strip()
        
        if price_text:
            # Clean and parse price
            price_clean = re.sub(r'[^\d.]', '', price_text)
            if price_clean:
                price = float(price_clean)
                return price, product_name
        
        return None, None
        
    except Exception as e:
        print(f"Error scraping price from {url}: {e}")
        return None, None


def create_github_issue(item_name, current_price, threshold, url):
    """
    Create a GitHub issue for price alert
    
    Args:
        item_name: Name of the item
        current_price: Current price
        threshold: Price threshold
        url: Product URL
    """
    github_token = os.environ.get('GITHUB_TOKEN')
    repo = os.environ.get('GITHUB_REPOSITORY')
    
    if not github_token or not repo:
        print("GitHub token or repository not configured. Skipping issue creation.")
        return
    
    savings = threshold - current_price
    
    issue_title = f"🎉 Price Alert: {item_name} - ${current_price:.2f}"
    issue_body = f"""## Price Drop Alert!

**Product:** {item_name}
**Current Price:** ${current_price:.2f}
**Your Threshold:** ${threshold:.2f}
**You Save:** ${savings:.2f}

The price has dropped to or below your target threshold!

**Product Link:** {url}

**Timestamp:** {datetime.now().isoformat()}

---
*This alert was automatically generated by the Costco Price Tracker.*
"""
    
    api_url = f"https://api.github.com/repos/{repo}/issues"
    headers = {
        'Authorization': f'token {github_token}',
        'Accept': 'application/vnd.github.v3+json'
    }
    
    data = {
        'title': issue_title,
        'body': issue_body,
        'labels': ['price-alert', 'automated']
    }
    
    try:
        response = requests.post(api_url, headers=headers, json=data)
        response.raise_for_status()
        print(f"✅ GitHub issue created for {item_name}")
    except Exception as e:
        print(f"❌ Failed to create GitHub issue: {e}")


def check_prices():
    """Main function to check prices for all configured items"""
    config = load_config()
    history = load_price_history()
    
    print("\n" + "=" * 80)
    print("COSTCO PRICE TRACKER - Automated Check")
    print("=" * 80)
    print(f"Timestamp: {datetime.now().isoformat()}")
    print(f"Checking {len(config['items'])} items...")
    print("=" * 80)
    
    alerts_triggered = 0
    
    for item in config['items']:
        item_id = item['item_id']
        item_name = item['name']
        threshold = item['price_threshold']
        url = item['url']
        
        print(f"\n[Checking] {item_name}")
        print(f"  Threshold: ${threshold:.2f} or less")
        print(f"  URL: {url}")
        
        # Scrape current price
        current_price, scraped_name = scrape_price_from_product_page(url)
        
        if current_price is None:
            print(f"  ❌ Failed to fetch price")
            continue
        
        print(f"  Current Price: ${current_price:.2f}")
        
        # Check if price is at or below threshold
        if current_price <= threshold:
            savings = threshold - current_price
            print(f"  ✅ ALERT: Price is ${savings:.2f} below/at threshold!")
            
            # Check if this is a new alert (price wasn't below threshold before)
            previous_data = history.get(item_id, {})
            previous_price = previous_data.get('price')
            previous_alert = previous_data.get('alert_triggered', False)
            
            # Only create issue if this is a new alert or price dropped further
            if not previous_alert or (previous_price and current_price < previous_price):
                if config['notification']['enabled']:
                    create_github_issue(item_name, current_price, threshold, url)
                    alerts_triggered += 1
            else:
                print(f"  ℹ️  Alert already active (no new issue created)")
        else:
            difference = current_price - threshold
            print(f"  ℹ️  Price is ${difference:.2f} above threshold")
        
        # Update history
        history[item_id] = {
            'name': item_name,
            'price': current_price,
            'threshold': threshold,
            'last_checked': datetime.now().isoformat(),
            'alert_triggered': current_price <= threshold
        }
    
    # Save updated history
    save_price_history(history)
    
    print("\n" + "=" * 80)
    print(f"Check Complete: {alerts_triggered} new alerts triggered")
    print("=" * 80 + "\n")
    
    # Exit with error code 1 if any alerts were triggered (to fail the workflow)
    # Exit with code 0 if no alerts (workflow passes)
    if alerts_triggered > 0:
        print("🚨 EXITING WITH ERROR CODE 1 - Price alert(s) triggered!")
        print("   GitHub Actions will fail and send you an email notification.")
        sys.exit(1)
    else:
        print("✅ EXITING WITH CODE 0 - No price alerts.")
        print("   All prices are above your thresholds.")
        sys.exit(0)


if __name__ == "__main__":
    check_prices()
